version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto8
    pre_build:
        commands:
            - echo "Pre_build"
    build:
        commands:
            - echo "Build"
            - cd src
            - mvn clean install
    post_build:
        commands:
            - echo "Post_build"
artifacts:
    files:
        - src/web/app/target/*.war
        - scripts/*.sh
        - appspec.yml
    discard-paths: yes